### ISSUE TITLE
Question about idea 

### ISSUE THREAD

**Issue by mrRobot1997** [Seideman-Group/AlignmentCalculator#1]
hi, i'm doing reseaches about how molecules act when they interact with lasers. I would like to know the idea of your code. If you have papers or articles please share for me.

**Comment by tpurcell90** [comment]
I did not write this code, but it solves the time dependent Schrodinger's Equation to get the alignment of a molecule interacting with a plane wave source. Some version of the code was used in these papers.

https://aip.scitation.org/doi/10.1063/1.4890344
https://pubs.acs.org/doi/10.1021/acs.jpcc.6b05476

**Comment by mrRobot1997** [comment]
i also have problems with installation. Can't run "make" command with your
folder

**Comment by mrRobot1997** [comment]
also, can you please tell me the author of this code please. it will help a
lot for my thesis

**Comment by tpurcell90** [comment]
@jeszekely  wrote it, but I don't know if he keeps track of this anymore since he has not worked on it in a few years

you have to run the configure script first to install it.

**Comment by Cmueller126** [comment]
The idea of this code is that through interaction with a moderately intense femtosecond laser pulse, one can generate a superposition of rotational states through an induced dipole transition, which is observable as alignment of the most polarizable axis of the molecule with the field.  The pulse is assumed to be far off resonant with any electronic states, and due to the timescale, vibrational couplings are also neglected. This code propagates the resulting wave packet in time in the absence of dissipative mechanisms, and is implemented for closed shell molecular rotors.  

Here are two of the papers that cover the fundamentals of what this code does.  I would also suggest Zare's Angular Momentum text for further understanding of the underlying physics.  
Stapelfeldt, H.; Seideman, T. Aligning molecules with strong laser pulses. Rev. Mod. Phys.
2003, 75, 543–557.
Seideman, T. Rotational excitation and molecular alignment in intense laser fields. J. Chem.
Phys. 1995, 103, 7887–7896.

**Comment by jeszekely** [comment]
What @Cmueller126 said is correct, but the code also includes an adiabatic rotational excitation as well (which boils down so a rather simple diagonalization of the rotational Hamiltonian + a field-matter interaction term). The references provided are a good source for understanding rotational alignment which I recommend before trying to decipher what this code is doing.

@tpurcell90 Yes, I still keep track of these things even though I don't actively work on them.

**Comment by mrRobot1997** [comment]
thank you so much

**Comment by mrRobot1997** [comment]
i would like to know how to run your code in this link
https://github.com/jeszekely/MolecularAlignment
